import {
  Accessibility,
  AppWindow,
  ArrowUpRight,
  Award,
  BellRing,
  Bot,
  Building2,
  Briefcase,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CloudCog,
  Code2,
  Compass,
  CreditCard,
  Database,
  Fingerprint,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Gamepad2,
  Heart,
  HeartPulse,
  Landmark,
  Layers,
  LayoutDashboard,
  Mail,
  MapPin,
  MessageCircle,
  Moon,
  MousePointerClick,
  MoveRight,
  Package,
  Palette,
  Plane,
  Play,
  PenTool,
  Rocket,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Truck,
  Users,
  UtensilsCrossed,
  Zap,
} from "lucide-react";

function ExploreIcon(props) {
  return (
    <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" fill="currentColor" {...props}>
      <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zm50.7-186.9L162.4 380.6c-19.4 7.5-38.5-11.6-31-31l55.5-144.3c3.3-8.5 9.9-15.1 18.4-18.4l144.3-55.5c19.4-7.5 38.5 11.6 31 31L325.1 306.7c-3.2 8.5-9.9 15.1-18.4 18.4zM288 256a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z" />
    </svg>
  );
}

const icons = {
  "arrow-up-right": ArrowUpRight,
  award: Award,
  bot: Bot,
  "building-2": Building2,
  briefcase: Briefcase,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "cloud-cog": CloudCog,
  "code-2": Code2,
  explore: ExploreIcon,
  "graduation-cap": GraduationCap,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  heart: Heart,
  landmark: Landmark,
  mail: Mail,
  "move-right": MoveRight,
  package: Package,
  palette: Palette,
  plane: Plane,
  play: Play,
  "pen-tool": PenTool,
  search: Search,
  send: Send,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  truck: Truck,
  users: Users,
  "utensils-crossed": UtensilsCrossed,
  "calendar-days": CalendarDays,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  moon: Moon,
  accessibility: Accessibility,
  "app-window": AppWindow,
  "bell-ring": BellRing,
  compass: Compass,
  "credit-card": CreditCard,
  database: Database,
  fingerprint: Fingerprint,
  gauge: Gauge,
  "git-branch": GitBranch,
  globe: Globe,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "mouse-pointer-click": MousePointerClick,
  rocket: Rocket,
  server: Server,
  "shield-check": ShieldCheck,
  zap: Zap,
};

export default function Icon({ name, ...props }) {
  const Component = icons[name] || Sparkles;
  return <Component aria-hidden="true" {...props} />;
}
